### ISSUE TITLE
Package Signature

### ISSUE THREAD

**Issue by brunommpreto** [megamaced/spotify-easyrpm#50]
Is there a package signature?

**Comment by megamaced** [comment]
spotify-easyrpm does not sign the spotify-client package after it is generated, this is because;

1) Many people will not have gpg signing keys set up for rpm package signing
2) Even if they do, signing the RPM will require user intervention (i.e entering their gpg password) which will break -quiet mode and also scheduled building

**Comment by megamaced** [comment]
closing as no further info
