### ISSUE TITLE
Misses dependency on libayatana-appindicator3-1

### ISSUE THREAD

**Issue by tvogel** [megamaced/spotify-easyrpm#64]
Currently, when I install the RPM, it doesn't detect when libayatana-appindicator3-1 is missing and leaves spotify fail with
```
spotify: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```
Thanks for `spotify-easyrpm`!

PS. This is on openSUSE Tumbleweed.

**Comment by enrichman** [comment]
Just encountered the same issue. I just installed it manually with `sudo zypper in libayatana-appindicator3` but nice to see that it was already fixed yesterday with https://github.com/megamaced/spotify-easyrpm/commit/1cc068d6cf94dc5284127bcd25930690ac6136af!

Kudos to @megamaced 

I tried this because the Flatpak version stopped working (a strange token 101 issue), and it worked flawlessly.

**Comment by megamaced** [comment]
Fix is waiting to be staged into the tumbleweed repositories
